### ISSUE TITLE
zed permission lookup-subjects is causing a segfault

### ISSUE THREAD

**Issue by reify-tanner-stirrat** [authzed/zed#212]
## Description
```console
➜  project git:(branch) ✗ zed version    
client: zed v0.9.1
1:26PM WRN the version of SpiceDB being called is out of date. See: https://github.com/authzed/spicedb/releases/tag/v1.17.0 latest-released-version=v1.17.0 this-version=v1.14.0
service: v1.14.0

➜  project git:(branch) ✗ zed permission lookup-subjects site:my_site granted role_binding
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x100f90e30]

goroutine 1 [running]:
github.com/authzed/zed/internal/commands.lookupSubjectsCmdFunc(0x101e22700?, {0x1400056c1e0, 0x3, 0x3?})
	internal/commands/permission.go:416 +0x470
github.com/spf13/cobra.(*Command).execute(0x101e22700, {0x1400056c150, 0x3, 0x3})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400028e000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	cmd/zed/main.go:70 +0x510
```

I have a `site` with a relation to a `role_binding` and not a whole lot else in my system. I'll try upgrading the CLI, and if that doesn't work, I'll try upgrading SpiceDB.

**Comment by reify-tanner-stirrat** [comment]
Update: same result on `0.10.0` of `zed`. Gonna try upgrading SpiceDB and seeing if that fixes things.

**Comment by reify-tanner-stirrat** [comment]
Update: upgrading SpiceDB to `v1.17.0` fixed it. Seems to be something version-specific but not sure why it would be. We can upgrade SpiceDB but that's not a great workaround for us.

**Comment by josephschorr** [comment]
@reify-tanner-stirrat its because we deprecated a field and `zed` is now accessing the new one. Since its been a few months and users can use older `zed` is necessary, closing this
